version: '3.9'
services:
  ml:
    build:
      context: .
    image: ${IMAGE_TAG:-machine-learning-image-tag}
    environment:
      - GUNICORN_PORT=8000
      - METRIC_PORT=9000
      - GUNICORN_LOG_LEVEL="info"
      - DJANGO_DEBUG="false"
